import plugin from 'tailwindcss/plugin'
import preflight from './plugins/preflight'
import gridlines from './plugins/gridlines'
import { DEFAULT_BASE, FRACTIONS_1_TO_2, FRACTIONS_1_TO_5, PERCENTAGES, PERCENTAGES_FRACTIONS, UNIT_FRACTIONS } from './constants'
import { generateFractionUtil, generateUnitMultipleString } from './utils'


module.exports = plugin(function(api:any) {
  const plugins = [preflight, gridlines]
  for (let plugin of plugins) plugin(api)
}, {
  theme: {
    base: DEFAULT_BASE,
    spacing: {
      px: '1px',
      '0': '0',
      ...UNIT_FRACTIONS,
      ...FRACTIONS_1_TO_5,
      ...generateFractionUtil('5 1/4'),
      ...generateFractionUtil('5 2/4'),
      ...generateFractionUtil('5 3/4'),
      ...generateFractionUtil('5 1/2'),
      ...generateFractionUtil('6'),
      ...generateFractionUtil('6 1/4'),
      ...generateFractionUtil('6 2/4'),
      ...generateFractionUtil('6 3/4'),
      ...generateFractionUtil('6 1/2'),
      ...generateFractionUtil('7'),
      ...generateFractionUtil('7 1/4'),
      ...generateFractionUtil('7 2/4'),
      ...generateFractionUtil('7 3/4'),
      ...generateFractionUtil('7 1/2'),
      ...generateFractionUtil('8'),
      ...generateFractionUtil('8 1/4'),
      ...generateFractionUtil('8 2/4'),
      ...generateFractionUtil('8 3/4'),
      ...generateFractionUtil('8 1/2'),
      ...generateFractionUtil('9'),
      ...generateFractionUtil('9 1/4'),
      ...generateFractionUtil('9 2/4'),
      ...generateFractionUtil('9 3/4'),
      ...generateFractionUtil('9 1/2'),
      ...generateFractionUtil('10'),
      ...generateFractionUtil('11'),
      ...generateFractionUtil('12'),
      ...generateFractionUtil('13'),
      ...generateFractionUtil('14'),
      ...generateFractionUtil('15'),
      ...generateFractionUtil('16'),
      ...generateFractionUtil('17'),
      ...generateFractionUtil('18'),
      ...generateFractionUtil('19'),
      ...generateFractionUtil('20'),
      ...generateFractionUtil('21'),
      ...generateFractionUtil('22'),
      ...generateFractionUtil('23'),
      ...generateFractionUtil('24'),
      ...generateFractionUtil('25'),
      ...generateFractionUtil('26'),
      ...generateFractionUtil('27'),
      ...generateFractionUtil('28'),
      ...generateFractionUtil('29'),
      ...generateFractionUtil('30'),
      ...generateFractionUtil('35'),
      ...generateFractionUtil('40'),
    },
    borderRadius: {
      none: '0',
      ...UNIT_FRACTIONS,
      ...FRACTIONS_1_TO_5,
      full: '9999px',
    },
    borderWidth: {
      default: '1px',
      '0': '0',
      ...UNIT_FRACTIONS
		},
    inset: (theme, { negative }) => ({
      auto: 'auto',
      ...theme('spacing'),
      ...negative(theme('spacing')),
      ...PERCENTAGES,
      ...PERCENTAGES_FRACTIONS,
      full: '100%',
      ...negative(PERCENTAGES),
      ...negative(PERCENTAGES_FRACTIONS),
      '-full': '-100%',
    }),
    lineHeight: {
      none: '1',
      tight: '1.25',
      snug: '1.375',
      normal: '1.5',
      relaxed: '1.625',
      loose: '2',
      ...UNIT_FRACTIONS,
      ...FRACTIONS_1_TO_2,
    },
    maxWidth: (theme, { breakpoints }) => ({
      none: 'none',
      ...theme('spacing'),
      ...theme('screens'),
      ...PERCENTAGES,
      ...PERCENTAGES_FRACTIONS,
      full: '100%',
      '1/4-screen': '25vw',
      '1/3-screen': '33vw',
      '1/2-screen': '50vw',
      '2/3-screen': '66vw',
      '3/4-screen': '75vw',
      screen: '100vw',
    }),
    minWidth: (theme) => ({
      '0': '0',
      ...theme('spacing'),
      ...theme('screens'),
      ...PERCENTAGES,
      ...PERCENTAGES_FRACTIONS,
      full: '100%',
      min: 'min-content',
      max: 'max-content',
      '1/4-screen': '25vw',
      '1/3-screen': '33vw',
      '1/2-screen': '50vw',
      '2/3-screen': '66vw',
      '3/4-screen': '75vw',
      screen: '100vw',
    }),
    width: theme => ({
      auto: 'auto',
      ...theme('spacing'),
      ...theme('screens'),
      ...PERCENTAGES,
      ...PERCENTAGES_FRACTIONS,
      full: '100%',
      '1/4-screen': '25vw',
      '1/3-screen': '33vw',
      '1/2-screen': '50vw',
      '2/3-screen': '66vw',
      '3/4-screen': '75vw',
      screen: '100vw',
    }),
    maxHeight: (theme) => ({
      none: 'none',
      ...theme('spacing'),
      ...PERCENTAGES,
      ...PERCENTAGES_FRACTIONS,
      full: '100%',
      '1/4-screen': '25vh',
      '1/3-screen': '33vh',
      '1/2-screen': '50vh',
      '2/3-screen': '66vh',
      '3/4-screen': '75vh',
      screen: '100vh',
    }),
    minHeight: (theme) => ({
      '0': '0',
      ...theme('spacing'),
      ...PERCENTAGES,
      ...PERCENTAGES_FRACTIONS,
      full: '100%',
      '1/4-screen': '25vh',
      '1/3-screen': '33vh',
      '1/2-screen': '50vh',
      '2/3-screen': '66vh',
      '3/4-screen': '75vh',
      screen: '100vh',
    }),
    height: theme => ({
      auto: 'auto',
      ...theme('spacing'),
      ...PERCENTAGES,
      ...PERCENTAGES_FRACTIONS,
      full: '100%',
      '1/4-screen': '25vh',
      '1/3-screen': '33vh',
      '1/2-screen': '50vh',
      '2/3-screen': '66vh',
      '3/4-screen': '75vh',
      screen: '100vh',
    }),
    gridlines: {
      ruleColor: 'rgba(255,255,255, 0.2)',
      ruleSecondaryColor: 'rgba(255,255,255, 0.1)'
    },
    ringOffsetWidth: {
      '0': '0',
      'px': '1px',
      ...UNIT_FRACTIONS
    },
    ringWidth: {
      DEFAULT: generateUnitMultipleString(0.125),
      '0': '0',
      'px': '1px',
      ...UNIT_FRACTIONS
    },
    textIndent: (theme, { negative }) => ({
      ...theme('lineHeight'),
      ...negative(theme('lineHeight'))
    }),
    translate: (theme, { negative }) => ({
      ...theme('spacing'),
      ...negative(theme('spacing')),
      ...PERCENTAGES,
      ...PERCENTAGES_FRACTIONS,
      full: '100%',
      ...negative(PERCENTAGES),
      ...negative(PERCENTAGES_FRACTIONS),
      '-full': '-100%',
    }),
	},
  variants: {
    textIndent: ['responsive'],
  },
})